### ISSUE TITLE
Compatible with 2.6.x

### ISSUE THREAD

**Issue by cheoAlejo** [tckz/redmine_wiki_preview_ext#1]
Very useful plugin. Any chance to make it compatible with 2.6.x ?

**Comment by tckz** [comment]
Thank you for trying the plugin.
I use redmine which were upgraded to 3.0. So, I have confirmed the plugin with Redmine 3.0 or higher only.

I think it works when version requirement was commented out like below.

in RAILS_ROOT/plugins/redmine_wiki_preview_ext/init.rb

``` ruby
  description 'Expand wiki preview.'
  version '0.3.0'
  #requires_redmine :version_or_higher => '3.0.0'
  url "http://passing.breeze.cc/mt/"
```

See line at 'requires_redmine'.

**Comment by cheoAlejo** [comment]
Yes it works, thanks for the tip.
